{% set name = "dataframe"  %}
{% set version = "0.2.1.3" %}

package:
  name: "{{ name }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f6c4b86132337790fbb31bf47cbb9a6d6e29e810ad4a62d2e81cb2f1b5780407

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - tabulate >=0.7.7
    - numpy >=1.11.0
    - scipy >=0.18.0
    - pytest >=2.9.2
    - nose ==1.3.7
    - sphinx >=1.4.5
  run:
    - python
    - tabulate >=0.7.7
    - numpy >=1.11.0
    - scipy >=0.18.0
    - pytest >=2.9.2
    - nose ==1.3.7
    - sphinx >=1.4.5

test:
  imports:
    - dataframe

about:
  home: https://github.com/dirmeier/dataframe
  license: GNU General Public License v3 (GPLv3)
  license_file: LICENSE
  summary: 'A data-frame implementation using method piping.'
  doc_url: https://pythonhosted.org/dataframe/
  dev_url: https://github.com/dirmeier/dataframe

