language: python

sudo: false

python:
  - "3.4"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - graphviz

before_install:
  - sudo apt-get build-dep python-scipy python-numpy
  - pip install numpy
  - pip install scipy

install:
  - pip install .
  - pip install -r requirements.txt

script: nosetests dataframe