language: python

sudo: false

python:
  - "3.4"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - graphviz

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  - conda update --yes conda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install: 
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  - python setup.py install
  - pip install .
  - pip install -r requirements.txt

script: nosetests dataframe