package:
  name: dataframe
  version: "0.2.1"

source:
  fn: dataframe-0.2.1.tar.gz
  url: https://pypi.python.org/packages/29/ee/3899b14feaff64d11c61405b3bd2a53ab71d42e1545e9ef869220a2bdeca/dataframe-0.2.1.tar.gz
  md5: 8028eb66477243c40277c9a4967f87d0

requirements:
  build:
    - python
    - setuptools
    - prettytable >=0.7.2
    - numpy >=1.11.0
    - scipy >=0.18.0
    - pytest >=2.9.2
    - nose ==1.3.7
    - sphinx >=1.4.5
  run:
    - python
    - prettytable >=0.7.2
    - numpy >=1.11.0
    - scipy >=0.18.0
    - pytest >=2.9.2
    - nose ==1.3.7
    - sphinx >=1.4.5

test:
  imports:
    - dataframe

about:
  home: https://github.com/dirmeier/dataframe
  license: GNU General Public License v3 (GPLv3)
  summary: 'A data-frame implementation using method piping.'
  license_family: GPL3

