package:
  name: dataframe
  version: "0.2.1.1"

source:
  git_rev: 0.2.1.1
  git_url: https://github.com/dirmeier/dataframe.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - tabulate >=0.7.7
    - numpy >=1.11.0
    - scipy >=0.18.0
    - pytest >=2.9.2
    - nose ==1.3.7
    - sphinx >=1.4.5
  run:
    - python
    - tabulate >=0.7.7
    - numpy >=1.11.0
    - scipy >=0.18.0
    - pytest >=2.9.2
    - nose ==1.3.7
    - sphinx >=1.4.5

test:
  imports:
    - dataframe

about:
  home: https://github.com/dirmeier/dataframe
  license: GNU General Public License v3 (GPLv3)
  summary: 'A data-frame implementation using method piping.'
  license_family: GPL3

